### PR TITLE
Log (WIP)

### PR DESCRIPTION
**Pull request by seamusabshere**

### CODE REVIEW

**Comment by seamusabshere** [comment]
@dkastner what's the status?

**Comment by emk** [comment]
@seamusabshere This is a work in progress and it uses older APIs from before I replaced the argument parser and overhauled how pod and service arguments are handled.

I'll quickly add one more API that will make this simple. Watch this space.

**Comment by emk** [comment]
@seamusabshere Discussion has moved back to the tracking issue: https://github.com/faradayio/cage/issues/7

**Comment by dkastner** [comment]
Moved to https://github.com/faradayio/cage/issues/7

**Pull request closed without merging**
